/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IsaRouteImport } from './routes/isa'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLedgerRouteImport } from './routes/api/ledger'
import { Route as ApiMerchantRouteImport } from './routes/api/merchant'
import { Route as ApiTickRouteImport } from './routes/api/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IsaRoute = IsaRouteImport.update({
  id: '/isa',
  path: '/isa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerRoute = ApiLedgerRouteImport.update({
  id: '/api/ledger',
  path: '/api/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMerchantRoute = ApiMerchantRouteImport.update({
  id: '/api/merchant',
  path: '/api/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTickRoute = ApiTickRouteImport.update({
  id: '/api/tick',
  path: '/api/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/isa': typeof IsaRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/merchant': typeof ApiMerchantRoute
  '/api/tick': typeof ApiTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/isa': typeof IsaRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/merchant': typeof ApiMerchantRoute
  '/api/tick': typeof ApiTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/isa': typeof IsaRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/merchant': typeof ApiMerchantRoute
  '/api/tick': typeof ApiTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/isa' | '/api/health' | '/api/ledger' | '/api/merchant' | '/api/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/isa' | '/api/health' | '/api/ledger' | '/api/merchant' | '/api/tick'
  id:
    | '__root__'
    | '/'
    | '/isa'
    | '/api/health'
    | '/api/ledger'
    | '/api/merchant'
    | '/api/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IsaRoute: typeof IsaRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLedgerRoute: typeof ApiLedgerRoute
  ApiMerchantRoute: typeof ApiMerchantRoute
  ApiTickRoute: typeof ApiTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isa': {
      id: '/isa'
      path: '/isa'
      fullPath: '/isa'
      preLoaderRoute: typeof IsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger': {
      id: '/api/ledger'
      path: '/api/ledger'
      fullPath: '/api/ledger'
      preLoaderRoute: typeof ApiLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/merchant': {
      id: '/api/merchant'
      path: '/api/merchant'
      fullPath: '/api/merchant'
      preLoaderRoute: typeof ApiMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tick': {
      id: '/api/tick'
      path: '/api/tick'
      fullPath: '/api/tick'
      preLoaderRoute: typeof ApiTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IsaRoute: IsaRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLedgerRoute: ApiLedgerRoute,
  ApiMerchantRoute: ApiMerchantRoute,
  ApiTickRoute: ApiTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
