/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as ApiBacktestRouteImport } from './routes/api/backtest'
import { Route as ApiLedgerRouteImport } from './routes/api/ledger'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as ApiTickRouteImport } from './routes/api/tick'
import { Route as ApiTradeRouteImport } from './routes/api/trade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBacktestRoute = ApiBacktestRouteImport.update({
  id: '/api/backtest',
  path: '/api/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerRoute = ApiLedgerRouteImport.update({
  id: '/api/ledger',
  path: '/api/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTickRoute = ApiTickRouteImport.update({
  id: '/api/tick',
  path: '/api/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradeRoute = ApiTradeRouteImport.update({
  id: '/api/trade',
  path: '/api/trade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/api/backtest': typeof ApiBacktestRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/review': typeof ApiReviewRoute
  '/api/tick': typeof ApiTickRoute
  '/api/trade': typeof ApiTradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/api/backtest': typeof ApiBacktestRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/review': typeof ApiReviewRoute
  '/api/tick': typeof ApiTickRoute
  '/api/trade': typeof ApiTradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/api/backtest': typeof ApiBacktestRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/review': typeof ApiReviewRoute
  '/api/tick': typeof ApiTickRoute
  '/api/trade': typeof ApiTradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/api/backtest'
    | '/api/ledger'
    | '/api/review'
    | '/api/tick'
    | '/api/trade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/api/backtest'
    | '/api/ledger'
    | '/api/review'
    | '/api/tick'
    | '/api/trade'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/api/backtest'
    | '/api/ledger'
    | '/api/review'
    | '/api/tick'
    | '/api/trade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  ApiBacktestRoute: typeof ApiBacktestRoute
  ApiLedgerRoute: typeof ApiLedgerRoute
  ApiReviewRoute: typeof ApiReviewRoute
  ApiTickRoute: typeof ApiTickRoute
  ApiTradeRoute: typeof ApiTradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backtest': {
      id: '/api/backtest'
      path: '/api/backtest'
      fullPath: '/api/backtest'
      preLoaderRoute: typeof ApiBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger': {
      id: '/api/ledger'
      path: '/api/ledger'
      fullPath: '/api/ledger'
      preLoaderRoute: typeof ApiLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tick': {
      id: '/api/tick'
      path: '/api/tick'
      fullPath: '/api/tick'
      preLoaderRoute: typeof ApiTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trade': {
      id: '/api/trade'
      path: '/api/trade'
      fullPath: '/api/trade'
      preLoaderRoute: typeof ApiTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  ApiBacktestRoute: ApiBacktestRoute,
  ApiLedgerRoute: ApiLedgerRoute,
  ApiReviewRoute: ApiReviewRoute,
  ApiTickRoute: ApiTickRoute,
  ApiTradeRoute: ApiTradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
